/**
 * Payroll CSV generation, ADP and Gusto.
 *
 * The core promise of the product is that approved hours leave as a file the
 * bookkeeper imports without re-keying. A broken export destroys that promise
 * (README Key Risk 6), so:
 *
 *  - The column maps are **data**, declared once, below.
 *  - The rendering is pure and pinned by golden-file tests.
 *  - A validator runs **before** generation and blocks on anything that would
 *    make the file unimportable — a missing ADP file number, a missing Gusto
 *    email, a shift still open inside the period.
 *  - The generated bytes and a SHA-256 of them are stored, so a re-download in
 *    August reproduces February's file exactly.
 *
 * Hours are hundredths of an hour, truncated, never rounded up (src/lib/time.ts).
 */

import { createHash } from "node:crypto";
import { and, asc, desc, eq, gte, isNull, lt } from "drizzle-orm";
import { getDb } from "@/db";
import {
  exportLineItems,
  payrollExports,
  timeEntries,
  users,
  type ExportFormat,
  type Organization,
  type TimeEntry,
  type User,
} from "@/db/schema";
import { csvDocument } from "@/lib/csv";
import { bucketByLocalDay, computeOvertimeSplit } from "@/lib/overtime";
import {
  centihoursToDecimal,
  localRangeUtc,
  parseDateKey,
  weekStartKey,
  weekStartKeyForDate,
  addDaysToDateKey,
} from "@/lib/time";
import { toShift } from "@/lib/time-entries";

/* ------------------------------------------------------------ format spec --- */

/** ADP RUN "Paydata" import: exact header casing and order. */
export const ADP_HEADER = [
  "Co Code",
  "Batch ID",
  "File #",
  "Reg Hours",
  "O/T Hours",
  "Pay Date",
] as const;

/** Gusto time-import template. */
export const GUSTO_HEADER = [
  "last_name",
  "first_name",
  "employee_email",
  "regular_hours",
  "overtime_hours",
] as const;

export interface ExportRow {
  userId: string;
  name: string;
  email: string | null;
  payrollFileNumber: string | null;
  regularCentihours: number;
  overtimeCentihours: number;
  timeEntryIds: string[];
}

/**
 * First/last split for Gusto. Everything up to the last space is the given
 * name, the final token is the surname — which is the only rule that survives
 * both "Dale Hendricks" and "Miguel Ángel Ríos Vega" without asking anyone to
 * re-enter their name. A single-token name cannot be split and is reported by
 * the validator rather than guessed at.
 */
export function splitName(name: string): { first: string; last: string } | null {
  const parts = name.trim().split(/\s+/).filter(Boolean);
  if (parts.length < 2) return null;
  return { first: parts.slice(0, -1).join(" "), last: parts[parts.length - 1] };
}

/** ADP wants MM/DD/YYYY. */
export function adpPayDate(dateKey: string): string {
  const { year, month, day } = parseDateKey(dateKey);
  return `${String(month).padStart(2, "0")}/${String(day).padStart(2, "0")}/${year}`;
}

/**
 * ADP Batch IDs are short and per-payroll. Deriving it from the period end
 * (MMDD) makes two exports of the same period land in the same batch, which is
 * what an accountant re-running an import expects.
 */
export function adpBatchId(periodEnd: string): string {
  const { month, day } = parseDateKey(periodEnd);
  return `${String(month).padStart(2, "0")}${String(day).padStart(2, "0")}`;
}

export function renderAdpCsv(
  rows: readonly ExportRow[],
  opts: { companyCode: string; periodEnd: string },
): string {
  const batchId = adpBatchId(opts.periodEnd);
  const payDate = adpPayDate(opts.periodEnd);
  const ordered = [...rows].sort(
    (a, b) =>
      (a.payrollFileNumber ?? "").localeCompare(b.payrollFileNumber ?? "", "en") ||
      a.name.localeCompare(b.name, "en"),
  );
  return csvDocument(
    ADP_HEADER,
    ordered.map((row) => [
      opts.companyCode,
      batchId,
      row.payrollFileNumber ?? "",
      centihoursToDecimal(row.regularCentihours),
      centihoursToDecimal(row.overtimeCentihours),
      payDate,
    ]),
  );
}

export function renderGustoCsv(rows: readonly ExportRow[]): string {
  const withNames = rows.map((row) => ({ row, split: splitName(row.name) }));
  const ordered = withNames.sort(
    (a, b) =>
      (a.split?.last ?? a.row.name).localeCompare(b.split?.last ?? b.row.name, "en") ||
      (a.split?.first ?? "").localeCompare(b.split?.first ?? "", "en"),
  );
  return csvDocument(
    GUSTO_HEADER,
    ordered.map(({ row, split }) => [
      split?.last ?? row.name,
      split?.first ?? "",
      row.email ?? "",
      centihoursToDecimal(row.regularCentihours),
      centihoursToDecimal(row.overtimeCentihours),
    ]),
  );
}

export function renderExport(
  format: ExportFormat,
  rows: readonly ExportRow[],
  opts: { companyCode: string; periodEnd: string },
): string {
  return format === "adp" ? renderAdpCsv(rows, opts) : renderGustoCsv(rows);
}

export function checksumOf(csv: string): string {
  return createHash("sha256").update(csv, "utf8").digest("hex").slice(0, 16);
}

/** "40.25 h" — for an email body or a history row, where a table is overkill. */
export function centihoursLabel(centihours: number): string {
  return `${centihoursToDecimal(centihours)} h`;
}

/* -------------------------------------------------------------- validation --- */

export type ExportIssueCode =
  | "missing_file_number"
  | "missing_email"
  | "missing_company_code"
  | "unsplittable_name"
  | "open_entry"
  | "unapproved"
  | "no_rows"
  | "period_splits_week";

export interface ExportIssue {
  code: ExportIssueCode;
  severity: "block" | "warn";
  userId?: string;
  name?: string;
  count?: number;
}

export interface ValidationContext {
  format: ExportFormat;
  adpCompanyCode: string | null;
  weekStartsOn: number;
  periodStart: string;
  periodEnd: string;
  openEntries: { userId: string; name: string }[];
  unapprovedCount: number;
}

/** Everything that could break the import, found before the file is written. */
export function validateExport(rows: readonly ExportRow[], ctx: ValidationContext): ExportIssue[] {
  const issues: ExportIssue[] = [];

  if (rows.length === 0) issues.push({ code: "no_rows", severity: "block" });

  if (ctx.format === "adp") {
    if (!ctx.adpCompanyCode?.trim()) {
      issues.push({ code: "missing_company_code", severity: "block" });
    }
    for (const row of rows) {
      if (!row.payrollFileNumber?.trim()) {
        issues.push({
          code: "missing_file_number",
          severity: "block",
          userId: row.userId,
          name: row.name,
        });
      }
    }
  } else {
    for (const row of rows) {
      if (!row.email?.trim()) {
        issues.push({ code: "missing_email", severity: "block", userId: row.userId, name: row.name });
      }
      if (!splitName(row.name)) {
        issues.push({
          code: "unsplittable_name",
          severity: "block",
          userId: row.userId,
          name: row.name,
        });
      }
    }
  }

  for (const open of ctx.openEntries) {
    issues.push({ code: "open_entry", severity: "block", userId: open.userId, name: open.name });
  }

  if (ctx.unapprovedCount > 0) {
    issues.push({ code: "unapproved", severity: "warn", count: ctx.unapprovedCount });
  }

  // Overtime is a workweek concept. A period that starts or ends mid-week can
  // only be split on the hours it contains, which may understate OT — say so
  // rather than quietly producing a number nobody can reconcile.
  const alignedStart = weekStartKeyForDate(ctx.periodStart, ctx.weekStartsOn) === ctx.periodStart;
  const alignedEnd =
    weekStartKeyForDate(addDaysToDateKey(ctx.periodEnd, 1), ctx.weekStartsOn) ===
    addDaysToDateKey(ctx.periodEnd, 1);
  if (!alignedStart || !alignedEnd) {
    issues.push({ code: "period_splits_week", severity: "warn" });
  }

  return issues;
}

export function blockingIssues(issues: readonly ExportIssue[]): ExportIssue[] {
  return issues.filter((i) => i.severity === "block");
}

/* ------------------------------------------------------------ collection --- */

/**
 * Turn a pay period into one row per worker.
 *
 * Overtime is computed **per payroll week** inside the period and then summed,
 * because 45 hours in week one and 35 in week two is 5 hours of OT, not zero.
 */
export async function collectExportRows(
  org: Organization,
  periodStart: string,
  periodEnd: string,
  now: Date = new Date(),
): Promise<ExportRow[]> {
  const db = getDb();
  const { start, end } = localRangeUtc(periodStart, periodEnd, org.timezone);

  const rows = await db
    .select({ entry: timeEntries, user: users })
    .from(timeEntries)
    .innerJoin(users, eq(users.id, timeEntries.userId))
    .where(
      and(
        eq(timeEntries.organizationId, org.id),
        gte(timeEntries.clockInAt, start),
        lt(timeEntries.clockInAt, end),
      ),
    )
    .orderBy(asc(users.name), asc(timeEntries.clockInAt));

  const byUser = new Map<string, { user: User; entries: TimeEntry[] }>();
  for (const row of rows) {
    const bucket = byUser.get(row.user.id) ?? { user: row.user, entries: [] };
    bucket.entries.push(row.entry);
    byUser.set(row.user.id, bucket);
  }

  const out: ExportRow[] = [];
  for (const { user, entries } of byUser.values()) {
    const byWeek = new Map<string, TimeEntry[]>();
    for (const entry of entries) {
      const key = weekStartKey(entry.clockInAt, org.timezone, org.weekStartsOn);
      byWeek.set(key, [...(byWeek.get(key) ?? []), entry]);
    }

    let regularCentihours = 0;
    let overtimeCentihours = 0;
    for (const weekEntries of byWeek.values()) {
      const buckets = bucketByLocalDay(
        weekEntries.map((e) => toShift(e, now)),
        org.timezone,
        now,
      );
      const split = computeOvertimeSplit(buckets, user.overtimeRule, org.otWeeklyThresholdHours);
      regularCentihours += split.regularCentihours;
      overtimeCentihours += split.overtimeCentihours;
    }

    out.push({
      userId: user.id,
      name: user.name,
      email: user.email,
      payrollFileNumber: user.payrollFileNumber,
      regularCentihours,
      overtimeCentihours,
      timeEntryIds: entries.map((e) => e.id),
    });
  }
  return out;
}

export async function openEntriesInPeriod(
  org: Organization,
  periodStart: string,
  periodEnd: string,
): Promise<{ userId: string; name: string }[]> {
  const db = getDb();
  const { start, end } = localRangeUtc(periodStart, periodEnd, org.timezone);
  const rows = await db
    .select({ userId: users.id, name: users.name })
    .from(timeEntries)
    .innerJoin(users, eq(users.id, timeEntries.userId))
    .where(
      and(
        eq(timeEntries.organizationId, org.id),
        gte(timeEntries.clockInAt, start),
        lt(timeEntries.clockInAt, end),
        isNull(timeEntries.clockOutAt),
      ),
    );
  return rows;
}

export async function unapprovedCount(
  org: Organization,
  periodStart: string,
  periodEnd: string,
): Promise<number> {
  const db = getDb();
  const { start, end } = localRangeUtc(periodStart, periodEnd, org.timezone);
  const rows = await db
    .select({ id: timeEntries.id })
    .from(timeEntries)
    .where(
      and(
        eq(timeEntries.organizationId, org.id),
        gte(timeEntries.clockInAt, start),
        lt(timeEntries.clockInAt, end),
        isNull(timeEntries.approvedAt),
      ),
    );
  return rows.length;
}

export async function validateBeforeExport(
  org: Organization,
  format: ExportFormat,
  periodStart: string,
  periodEnd: string,
): Promise<{ rows: ExportRow[]; issues: ExportIssue[] }> {
  const rows = await collectExportRows(org, periodStart, periodEnd);
  const issues = validateExport(rows, {
    format,
    adpCompanyCode: org.adpCompanyCode,
    weekStartsOn: org.weekStartsOn,
    periodStart,
    periodEnd,
    openEntries: await openEntriesInPeriod(org, periodStart, periodEnd),
    unapprovedCount: await unapprovedCount(org, periodStart, periodEnd),
  });
  return { rows, issues };
}

/* ------------------------------------------------------------- generation --- */

export class ExportBlocked extends Error {
  constructor(public issues: ExportIssue[]) {
    super("Export blocked by validation");
  }
}

export interface GeneratedExport {
  id: string;
  csv: string;
  checksum: string;
  rowCount: number;
  totalCentihours: number;
  fileKey: string;
  rows: ExportRow[];
  issues: ExportIssue[];
}

export async function generateExport(
  org: Organization,
  format: ExportFormat,
  periodStart: string,
  periodEnd: string,
  generatedBy: User,
): Promise<GeneratedExport> {
  const { rows, issues } = await validateBeforeExport(org, format, periodStart, periodEnd);
  const blocking = blockingIssues(issues);
  if (blocking.length > 0) throw new ExportBlocked(issues);

  const csv = renderExport(format, rows, {
    companyCode: org.adpCompanyCode ?? "",
    periodEnd,
  });
  const checksum = checksumOf(csv);
  const totalCentihours = rows.reduce(
    (sum, r) => sum + r.regularCentihours + r.overtimeCentihours,
    0,
  );
  const fileKey = `${org.id}/${format}-${periodStart}_${periodEnd}-${checksum}.csv`;

  const db = getDb();
  const [record] = await db
    .insert(payrollExports)
    .values({
      organizationId: org.id,
      format,
      periodStart,
      periodEnd,
      status: "generated",
      fileKey,
      csv,
      checksum,
      rowCount: rows.length,
      totalCentihours,
      generatedBy: generatedBy.id,
    })
    .returning();

  if (rows.length) {
    await db.insert(exportLineItems).values(
      rows.map((row) => ({
        payrollExportId: record.id,
        userId: row.userId,
        regularCentihours: row.regularCentihours,
        overtimeCentihours: row.overtimeCentihours,
        timeEntryIds: row.timeEntryIds,
      })),
    );
  }

  return {
    id: record.id,
    csv,
    checksum,
    rowCount: rows.length,
    totalCentihours,
    fileKey,
    rows,
    issues,
  };
}

export async function listExports(organizationId: string) {
  const db = getDb();
  return db
    .select()
    .from(payrollExports)
    .where(eq(payrollExports.organizationId, organizationId))
    .orderBy(desc(payrollExports.createdAt))
    .limit(20);
}

export async function getExport(organizationId: string, id: string) {
  const db = getDb();
  const [row] = await db
    .select()
    .from(payrollExports)
    .where(and(eq(payrollExports.id, id), eq(payrollExports.organizationId, organizationId)));
  return row ?? null;
}

export async function markDelivered(id: string, email: string): Promise<void> {
  const db = getDb();
  await db.update(payrollExports).set({ deliveredTo: email }).where(eq(payrollExports.id, id));
}
