import { chromium } from "playwright";
const SP="/tmp/claude-0/-home-user-Projects-/1ca38fdf-0b29-57e3-b349-c2f61fec860e/scratchpad/ss42";
const b=await chromium.launch({executablePath:"/opt/pw-browsers/chromium_headless_shell-1194/chrome-linux/headless_shell"});
const c=await b.newContext({viewport:{width:390,height:844},deviceScaleFactor:2,isMobile:true,hasTouch:true,storageState:`${SP}/state.json`});
const p=await c.newPage();
p.on("pageerror",e=>console.log("pageerror",String(e)));
await p.goto(`http://localhost:3042/apis/payments-api/diffs/${process.argv[2]}`,{waitUntil:"load"});
await p.waitForTimeout(800);
const t0 = await p.locator("main").first().innerText();
console.log("  before:", /\d+ BREAKING[^\n]*/.exec(t0)?.[0]);
console.log("  PR context shown:", /#42/.test(t0));
await p.locator('button:has-text("Acknowledge")').first().click();
await p.waitForSelector('textarea[name="note"]');
const scopeVisible = await p.locator('input[name="scope"][value="pr"]').isVisible().catch(()=>false);
console.log("  PR-scope option offered:", scopeVisible);
await p.fill('textarea[name="note"]', "Intentional: cancelled maps to refunded from 1 Aug. Acme signed off in PR 42.");
await p.waitForTimeout(150);
const hold = p.locator('button:has-text("Hold to acknowledge")').first();
const box = await hold.boundingBox();
await p.mouse.move(box.x+box.width/2, box.y+box.height/2);
await p.mouse.down(); await p.waitForTimeout(750); await p.mouse.up();
await p.waitForLoadState("load"); await p.waitForTimeout(1800);
const t1 = await p.locator("main").first().innerText();
console.log("  after :", /\d+ BREAKING[^\n]*/.exec(t1)?.[0]);
await p.screenshot({path:`${SP}/shots/44-ack-pr-scope.png`,fullPage:true});
await b.close();
