import { chromium } from "playwright";
const SP="/tmp/claude-0/-home-user-Projects-/1ca38fdf-0b29-57e3-b349-c2f61fec860e/scratchpad/ss42";
const b=await chromium.launch({executablePath:"/opt/pw-browsers/chromium_headless_shell-1194/chrome-linux/headless_shell"});
const c=await b.newContext({viewport:{width:390,height:844},hasTouch:true,isMobile:true,storageState:`${SP}/state.json`});
const p=await c.newPage();
p.on("console", m => console.log(`  [${m.type()}]`, m.text().slice(0,120)));
p.on("request", r => { if (r.method()==="POST") console.log("  POST action"); });
await p.goto(`http://localhost:3042/apis/payments-api/diffs/${process.argv[2]}`,{waitUntil:"load"});
await p.waitForTimeout(900);
const card = p.locator("article.card").nth(0);
await card.locator('button:has-text("Acknowledge")').first().click();
await p.waitForSelector('textarea[name="note"]');
await card.locator('textarea[name="note"]').fill("Intentional: shipped_at is null while a shipment is pending. Consumers were told.");
await p.waitForTimeout(200);
await p.evaluate(() => {
  const btn = [...document.querySelectorAll("button.btn-secondary")].find(b => b.textContent.includes("Hold"));
  for (const ev of ["pointerdown","pointerup","pointerleave","click"]) btn.addEventListener(ev, () => console.log("EV", ev));
});
const hold = card.locator('button:has-text("Hold to acknowledge")').first();
const box = await hold.boundingBox();
console.log("box", JSON.stringify(box));
await p.mouse.move(box.x + box.width/2, box.y + box.height/2);
await p.mouse.down();
await p.waitForTimeout(300);
console.log("holding class after 300ms:", await hold.getAttribute("class"));
await p.waitForTimeout(500);
await p.mouse.up();
await p.waitForTimeout(2200);
const t = await p.locator("main").first().innerText();
console.log("counts:", /\d+ BREAKING[^\n]*/.exec(t)?.[0]);
await b.close();
