import { chromium } from "playwright";
const SP="/tmp/claude-0/-home-user-Projects-/1ca38fdf-0b29-57e3-b349-c2f61fec860e/scratchpad/ss42";
const b=await chromium.launch({executablePath:"/opt/pw-browsers/chromium_headless_shell-1194/chrome-linux/headless_shell"});
const c=await b.newContext({viewport:{width:390,height:844},deviceScaleFactor:2,storageState:`${SP}/state.json`});
const p=await c.newPage();
p.on("pageerror",e=>console.log("pageerror",String(e)));
await p.goto(`http://localhost:3042/apis/payments-api/diffs/${process.argv[2]}`,{waitUntil:"load"});
await p.waitForTimeout(800);
// second card (enum removal), which has no existing ack
const cards = p.locator("article.card");
console.log("cards:", await cards.count());
const card = cards.nth(1);
console.log("card 2 title:", (await card.innerText()).split("\n").slice(0,3).join(" | "));
await card.locator('button:has-text("Acknowledge")').first().click();
await p.waitForSelector('textarea[name="note"]');
const checked = await p.locator('input[name="scope"]:checked').getAttribute("value").catch(()=>null);
console.log("checked scope:", checked);
await card.locator('textarea[name="note"]').fill("Intentional for PR 42 only: cancelled maps to refunded from 1 Aug.");
await p.waitForTimeout(150);
const hold = card.locator('button:has-text("Hold to acknowledge")').first();
const box = await hold.boundingBox();
await p.mouse.move(box.x+box.width/2, box.y+box.height/2);
await p.mouse.down(); await p.waitForTimeout(750); await p.mouse.up();
await p.waitForLoadState("load"); await p.waitForTimeout(2000);
const t = await p.locator("main").first().innerText();
console.log("counts:", /\d+ BREAKING[^\n]*/.exec(t)?.[0]);
const err = /(That diff|Write a note|This diff did not|Acknowledged\.)[^\n]*/.exec(t);
console.log("message:", err?.[0] ?? "(none)");
await b.close();
