/**
 * A small PDF text-layer reader.
 *
 * Most utility bills arrive as PDFs generated by a billing system, which means they
 * carry a real text layer. Reading it costs nothing and is deterministic, so the
 * pipeline tries it *before* any model call: on a text-bearing bill the arithmetic can
 * be grounded in characters that are actually in the file rather than in a model's
 * reading of a picture of them.
 *
 * What it does: walk the page content streams, track the current font, and decode the
 * operands of the text-showing operators (`Tj`, `TJ`, `'`, `"`) through that font's
 * `/ToUnicode` CMap. Subset fonts — which is what every modern PDF generator emits —
 * encode glyph indices, not characters, so without the CMap "Total kWh used 4,182" comes
 * out as "7RWDONULHXVHG" and a naive reader would report a plausible-looking wrong
 * number. That is the exact failure this file exists to prevent.
 *
 * What it does not do: layout reconstruction beyond newlines at line-positioning
 * operators, CID fonts with a non-Identity encoding, or OCR. A scanned bill has no text
 * layer and returns "", which is the signal to fall back to vision extraction — never a
 * signal to invent a number.
 *
 * **The safety rule: decode exactly, or not at all.** Where a font's CMap is missing or
 * ambiguous, its text is dropped rather than guessed, and a document whose text cannot be
 * decoded reaches the operator as a review item with empty fields.
 */

import { inflateSync } from "node:zlib";

const MAX_PAGES = 40;

export function looksLikePdf(bytes: Uint8Array): boolean {
  return (
    bytes.length > 4 &&
    bytes[0] === 0x25 &&
    bytes[1] === 0x50 &&
    bytes[2] === 0x44 &&
    bytes[3] === 0x46
  );
}

interface RawObject {
  dict: string;
  /** Still-encoded stream body, latin1. Undefined when the object has no stream. */
  stream?: string;
}

/** Split the file into indirect objects. Good enough for the generators bills come from. */
function parseObjects(raw: string): Map<number, RawObject> {
  const out = new Map<number, RawObject>();
  const re = /(?:^|[\s>])(\d+)\s+\d+\s+obj\b/g;
  let m: RegExpExecArray | null;
  while ((m = re.exec(raw)) !== null) {
    const num = Number(m[1]);
    const bodyStart = m.index + m[0].length;
    const endObj = raw.indexOf("endobj", bodyStart);
    if (endObj === -1) continue;
    const body = raw.slice(bodyStart, endObj);
    const streamAt = body.indexOf("stream");
    if (streamAt === -1) {
      out.set(num, { dict: body });
    } else {
      const dict = body.slice(0, streamAt);
      let stream = body.slice(streamAt + "stream".length);
      stream = stream.replace(/^\r?\n/, "");
      const endStream = stream.lastIndexOf("endstream");
      out.set(num, { dict, stream: endStream === -1 ? stream : stream.slice(0, endStream) });
    }
    re.lastIndex = endObj;
  }
  return out;
}

function decodeStream(obj: RawObject): string {
  if (obj.stream === undefined) return "";
  if (/\/FlateDecode/.test(obj.dict)) {
    try {
      return inflateSync(Buffer.from(obj.stream, "latin1")).toString("latin1");
    } catch {
      return "";
    }
  }
  if (/\/DCTDecode|\/JPXDecode|\/CCITTFaxDecode|\/JBIG2Decode/.test(obj.dict)) return "";
  return obj.stream;
}

/* --------------------------------------------------------------- ToUnicode --- */

type CMap = Map<number, string>;

function codeUnits(hex: string): string {
  let out = "";
  for (let i = 0; i + 3 < hex.length; i += 4) {
    out += String.fromCharCode(parseInt(hex.slice(i, i + 4), 16));
  }
  if (hex.length === 2) out = String.fromCharCode(parseInt(hex, 16));
  return out;
}

/** Parse a `/ToUnicode` CMap stream into code → string. */
export function parseToUnicode(cmap: string): CMap {
  const map: CMap = new Map();

  for (const block of cmap.match(/beginbfchar([\s\S]*?)endbfchar/g) ?? []) {
    const pairs = block.match(/<([0-9A-Fa-f]+)>\s*<([0-9A-Fa-f]*)>/g) ?? [];
    for (const pair of pairs) {
      const m = /<([0-9A-Fa-f]+)>\s*<([0-9A-Fa-f]*)>/.exec(pair);
      if (!m) continue;
      map.set(parseInt(m[1], 16), codeUnits(m[2]));
    }
  }

  for (const block of cmap.match(/beginbfrange([\s\S]*?)endbfrange/g) ?? []) {
    // <lo> <hi> <dst>  or  <lo> <hi> [<d1> <d2> …]
    const re = /<([0-9A-Fa-f]+)>\s*<([0-9A-Fa-f]+)>\s*(?:<([0-9A-Fa-f]*)>|\[([\s\S]*?)\])/g;
    let m: RegExpExecArray | null;
    while ((m = re.exec(block)) !== null) {
      const lo = parseInt(m[1], 16);
      const hi = parseInt(m[2], 16);
      if (hi < lo || hi - lo > 65_535) continue;
      if (m[3] !== undefined) {
        const base = parseInt(m[3], 16);
        for (let c = lo; c <= hi; c += 1) {
          map.set(c, String.fromCharCode(base + (c - lo)));
        }
      } else if (m[4] !== undefined) {
        const items = m[4].match(/<([0-9A-Fa-f]*)>/g) ?? [];
        items.forEach((item, i) => {
          const hexInner = item.slice(1, -1);
          map.set(lo + i, codeUnits(hexInner));
        });
      }
    }
  }

  return map;
}

function conflicts(a: CMap, b: CMap): boolean {
  for (const [code, ch] of b) {
    const existing = a.get(code);
    if (existing !== undefined && existing !== ch) return true;
  }
  return false;
}

/* ---------------------------------------------------------------- extraction --- */

interface FontInfo {
  cmap: CMap | null;
  /** Identity-H and other 2-byte encodings read hex operands two bytes at a time. */
  twoByte: boolean;
}

export function pdfText(bytes: Uint8Array): string {
  if (!looksLikePdf(bytes)) return "";
  const raw = Buffer.from(bytes).toString("latin1");
  const objects = parseObjects(raw);
  if (objects.size === 0) return "";

  const pages = [...objects.entries()].filter(([, o]) => /\/Type\s*\/Page\b/.test(o.dict));
  const out: string[] = [];
  let pageCount = 0;
  let sawShowOperator = false;

  for (const [, page] of pages) {
    if (pageCount >= MAX_PAGES) break;
    pageCount += 1;

    const fonts = fontsFor(page.dict, objects);
    for (const contentNum of contentRefs(page.dict)) {
      const obj = objects.get(contentNum);
      if (!obj) continue;
      const content = decodeStream(obj);
      if (!content) continue;
      if (/\bTj\b|\bTJ\b/.test(content)) sawShowOperator = true;
      out.push(showTextOperands(content, fonts));
    }
  }

  // Some producers put text in a form XObject rather than the page stream. Fall back to
  // every decodable stream only when the page walk found no text operators at all — if it
  // found them and decoded nothing, that was a deliberate refusal (an undecodable subset
  // font) and re-reading the same bytes with a looser font table would produce exactly the
  // glyph soup the refusal existed to prevent.
  if (!sawShowOperator && out.join("").trim().length === 0) {
    const anyFonts = allFonts(objects);
    for (const [, obj] of objects) {
      if (obj.stream === undefined) continue;
      const content = decodeStream(obj);
      if (/\bTj\b|\bTJ\b/.test(content)) out.push(showTextOperands(content, anyFonts));
    }
  }

  return collapse(out.join("\n"));
}

/** `/Contents 6 0 R` or `/Contents [6 0 R 7 0 R]`. */
function contentRefs(pageDict: string): number[] {
  const single = /\/Contents\s+(\d+)\s+\d+\s+R/.exec(pageDict);
  if (single) return [Number(single[1])];
  const arr = /\/Contents\s*\[([^\]]*)\]/.exec(pageDict);
  if (!arr) return [];
  return [...arr[1].matchAll(/(\d+)\s+\d+\s+R/g)].map((m) => Number(m[1]));
}

/** Resolve the page's `/Font << /F4 4 0 R … >>` into decoders. */
function fontsFor(pageDict: string, objects: Map<number, RawObject>): Map<string, FontInfo> {
  const fonts = new Map<string, FontInfo>();
  const fontDict = /\/Font\s*<<([\s\S]*?)>>/.exec(pageDict);
  if (!fontDict) return fonts;
  for (const m of fontDict[1].matchAll(/\/([A-Za-z0-9_.+-]+)\s+(\d+)\s+\d+\s+R/g)) {
    const info = fontInfo(Number(m[2]), objects);
    if (info) fonts.set(m[1], info);
  }
  return fonts;
}

function fontInfo(objNum: number, objects: Map<number, RawObject>): FontInfo | null {
  const font = objects.get(objNum);
  if (!font) return null;
  const twoByte =
    /\/Type0\b/.test(font.dict) ||
    /\/Identity-H\b/.test(font.dict) ||
    /\/Identity-V\b/.test(font.dict);
  const toUni = /\/ToUnicode\s+(\d+)\s+\d+\s+R/.exec(font.dict);
  if (!toUni) return { cmap: null, twoByte };
  const cmapObj = objects.get(Number(toUni[1]));
  if (!cmapObj) return { cmap: null, twoByte };
  const cmap = parseToUnicode(decodeStream(cmapObj));
  return { cmap: cmap.size > 0 ? cmap : null, twoByte };
}

/**
 * Fallback font table for the "text lives in an XObject" case: every font in the file,
 * merged. A code that two subsets disagree about is dropped from the merged map — losing
 * a character is recoverable, printing the wrong one is not.
 */
function allFonts(objects: Map<number, RawObject>): Map<string, FontInfo> {
  const merged: CMap = new Map();
  let twoByte = false;
  let conflicted = false;
  for (const [num, obj] of objects) {
    if (!/\/Type\s*\/Font\b/.test(obj.dict)) continue;
    const info = fontInfo(num, objects);
    if (!info) continue;
    // Recorded before the CMap check: a two-byte font whose CMap is missing still means
    // "these operands are glyph indices", which is what makes refusing them correct.
    twoByte = twoByte || info.twoByte;
    if (!info.cmap) continue;
    if (conflicts(merged, info.cmap)) {
      conflicted = true;
      continue;
    }
    for (const [code, ch] of info.cmap) merged.set(code, ch);
  }
  if (conflicted && merged.size === 0) return new Map();
  const fonts = new Map<string, FontInfo>();
  fonts.set("*", { cmap: merged.size > 0 ? merged : null, twoByte });
  return fonts;
}

/**
 * Pull the operands of the text-showing operators out of one content stream.
 *
 * The subtle part is when a *line* ends. `Td` is not a line break: PDF generators emit it
 * mid-word to kern a pair of glyphs, so treating every `Td` as a newline splits
 * "4,110" into "4,1" and "10" — and a reader that then takes the first fragment reports
 * 41 kWh for a 4,110 kWh bill. So the vertical component decides: a `Td`/`TD` with a
 * non-zero `ty`, a `Tm` that moves the baseline, or `T*` breaks the line; everything else
 * continues it.
 */
function showTextOperands(content: string, fonts: Map<string, FontInfo>): string {
  const lines: string[] = [];
  let current = "";
  let pending: { hex: boolean; value: string }[] = [];
  let font: FontInfo | null = fonts.get("*") ?? null;
  let numbers: number[] = [];
  let lastBaseline: number | null = null;
  let inArray = false;

  const breakLine = () => {
    if (current.trim()) lines.push(current);
    current = "";
  };

  const re =
    /\/([A-Za-z0-9_.+-]+)\s+[\d.]+\s+Tf|\((?:\\.|[^\\()])*\)|<[0-9A-Fa-f\s]*>|-?\d*\.?\d+|\[|\]|\bTJ\b|\bTj\b|\bT\*\b|\bTd\b|\bTD\b|\bTm\b|\bET\b|\bBT\b|'|"/g;

  let m: RegExpExecArray | null;
  while ((m = re.exec(content)) !== null) {
    const tok = m[0];

    if (tok.endsWith("Tf")) {
      font = fonts.get(m[1] ?? "") ?? fonts.get("*") ?? null;
      numbers = [];
      continue;
    }
    if (tok === "[") {
      inArray = true;
      continue;
    }
    if (tok === "]") {
      inArray = false;
      continue;
    }
    if (/^-?\d*\.?\d+$/.test(tok)) {
      // Numbers inside a TJ array are kerning adjustments, not operands.
      if (!inArray) numbers.push(Number(tok));
      continue;
    }
    if (tok.startsWith("(")) {
      pending.push({ hex: false, value: tok.slice(1, -1) });
      continue;
    }
    if (tok.startsWith("<")) {
      pending.push({ hex: true, value: tok.slice(1, -1).replace(/\s+/g, "") });
      continue;
    }

    if (tok === "Tj" || tok === "TJ" || tok === "'" || tok === '"') {
      current += pending.map((p) => decodeOperand(p, font)).join("");
      pending = [];
      numbers = [];
      if (tok === "'" || tok === '"') breakLine();
      continue;
    }

    if (tok === "Td" || tok === "TD") {
      const ty = numbers.length >= 2 ? numbers[numbers.length - 1] : 0;
      if (Math.abs(ty) > 0.01) breakLine();
      numbers = [];
      pending = [];
      continue;
    }

    if (tok === "Tm") {
      const baseline = numbers.length >= 6 ? numbers[numbers.length - 1] : null;
      if (baseline !== null && lastBaseline !== null && Math.abs(baseline - lastBaseline) > 0.01) {
        breakLine();
      }
      if (baseline !== null) lastBaseline = baseline;
      numbers = [];
      pending = [];
      continue;
    }

    if (tok === "T*" || tok === "ET") {
      breakLine();
      numbers = [];
      pending = [];
      continue;
    }

    if (tok === "BT") {
      numbers = [];
      pending = [];
    }
  }
  breakLine();
  return lines.join("\n");
}

function decodeOperand(operand: { hex: boolean; value: string }, font: FontInfo | null): string {
  const codes: number[] = [];
  if (operand.hex) {
    const hex = operand.value;
    const step = font?.twoByte || hex.length % 4 === 0 ? 4 : 2;
    for (let i = 0; i + step <= hex.length; i += step) {
      codes.push(parseInt(hex.slice(i, i + step), 16));
    }
  } else {
    const bytes = unescapeLiteral(operand.value);
    if (font?.twoByte) {
      for (let i = 0; i + 1 < bytes.length; i += 2) {
        codes.push((bytes.charCodeAt(i) << 8) | bytes.charCodeAt(i + 1));
      }
    } else {
      for (let i = 0; i < bytes.length; i += 1) codes.push(bytes.charCodeAt(i));
    }
  }

  if (font?.cmap) {
    let out = "";
    for (const code of codes) {
      const ch = font.cmap.get(code);
      // An un-mapped code in a subset font is not a character we may guess at.
      if (ch !== undefined) out += ch;
    }
    return out;
  }

  // No CMap. A single-byte font is almost always a standard encoding, so the bytes are
  // the characters. A two-byte font without a CMap carries glyph indices, and those are
  // not text — dropping them is the only safe answer.
  if (font?.twoByte) return "";
  return codes.map((c) => String.fromCharCode(c)).join("");
}

function unescapeLiteral(s: string): string {
  return s.replace(/\\([nrtbf()\\]|[0-7]{1,3})/g, (_all, esc: string) => {
    switch (esc) {
      case "n":
        return "\n";
      case "r":
        return "\r";
      case "t":
        return "\t";
      case "b":
        return "\b";
      case "f":
        return "\f";
      case "(":
        return "(";
      case ")":
        return ")";
      case "\\":
        return "\\";
      default:
        return String.fromCharCode(parseInt(esc, 8));
    }
  });
}

function collapse(s: string): string {
  return s
    .replace(/\r\n?/g, "\n")
    .replace(/ /g, " ")
    .replace(/[ \t]+/g, " ")
    .split("\n")
    .map((l) => l.trim())
    .filter((l) => l.length > 0)
    .join("\n")
    .slice(0, 20_000);
}
