/**
 * A small PDF text-layer reader.
 *
 * Most utility bills arrive as PDFs generated by a billing system, which means they
 * carry a real text layer. Reading it costs nothing and is deterministic, so the
 * pipeline tries it *before* any model call: on a text-bearing bill the arithmetic
 * can be grounded in characters that are actually in the file rather than in a
 * model's reading of a picture of them.
 *
 * Scope, honestly stated: this walks content streams, inflates the FlateDecode ones,
 * and pulls the operands of the text-showing operators (`Tj`, `TJ`, `'`, `"`). It
 * does not do font encoding tables, CID mapping, or layout reconstruction beyond
 * newlines at line-positioning operators. A scanned bill has no text layer at all
 * and returns "", which is the signal to fall back to vision extraction — never a
 * signal to invent a number.
 */

import { inflateSync } from "node:zlib";

const MAX_STREAMS = 400;

export function looksLikePdf(bytes: Uint8Array): boolean {
  return (
    bytes.length > 4 &&
    bytes[0] === 0x25 &&
    bytes[1] === 0x50 &&
    bytes[2] === 0x44 &&
    bytes[3] === 0x46
  );
}

/** Extract whatever text a PDF's content streams carry. "" when there is none. */
export function pdfText(bytes: Uint8Array): string {
  if (!looksLikePdf(bytes)) return "";
  const raw = Buffer.from(bytes).toString("latin1");
  const out: string[] = [];
  let cursor = 0;
  let streams = 0;

  while (streams < MAX_STREAMS) {
    const start = raw.indexOf("stream", cursor);
    if (start === -1) break;
    const end = raw.indexOf("endstream", start);
    if (end === -1) break;
    streams += 1;

    // The dictionary immediately before the keyword says how the stream is encoded.
    const dict = raw.slice(Math.max(0, start - 400), start);
    let body = raw.slice(start + "stream".length, end);
    // A stream keyword is followed by CRLF or LF, never by nothing.
    body = body.replace(/^\r?\n/, "");

    let text = "";
    if (/\/FlateDecode/.test(dict)) {
      try {
        text = inflateSync(Buffer.from(body, "latin1")).toString("latin1");
      } catch {
        text = "";
      }
    } else if (!/\/DCTDecode|\/JPXDecode|\/CCITTFaxDecode|\/Image/.test(dict)) {
      text = body;
    }
    if (text) out.push(showTextOperands(text));
    cursor = end + "endstream".length;
  }

  return collapse(out.join("\n"));
}

/** Pull the operands of the text-showing operators out of one content stream. */
function showTextOperands(content: string): string {
  const lines: string[] = [];
  let current = "";
  // Matches: (literal) Tj | (literal) ' | [ ... ] TJ | <hex> Tj | Td/TD/T*/ET
  const re = /\((?:\\.|[^\\()])*\)|<[0-9A-Fa-f\s]+>|\[|\]|\bTJ\b|\bTj\b|\bT\*\b|\bTd\b|\bTD\b|\bET\b|\bBT\b|'|"/g;
  let pending: string[] = [];
  let m: RegExpExecArray | null;
  while ((m = re.exec(content)) !== null) {
    const tok = m[0];
    if (tok.startsWith("(")) {
      pending.push(decodeLiteral(tok.slice(1, -1)));
    } else if (tok.startsWith("<")) {
      pending.push(decodeHex(tok.slice(1, -1)));
    } else if (tok === "Tj" || tok === "TJ" || tok === "'" || tok === '"') {
      current += pending.join("");
      pending = [];
      if (tok === "'" || tok === '"') {
        lines.push(current);
        current = "";
      }
    } else if (tok === "Td" || tok === "TD" || tok === "T*" || tok === "ET") {
      if (current.trim()) lines.push(current);
      current = "";
      pending = [];
    }
  }
  if (current.trim()) lines.push(current);
  return lines.join("\n");
}

function decodeLiteral(s: string): string {
  return s.replace(/\\([nrtbf()\\]|[0-7]{1,3})/g, (_all, esc: string) => {
    switch (esc) {
      case "n":
        return "\n";
      case "r":
        return "\r";
      case "t":
        return "\t";
      case "b":
        return "\b";
      case "f":
        return "\f";
      case "(":
        return "(";
      case ")":
        return ")";
      case "\\":
        return "\\";
      default:
        return String.fromCharCode(parseInt(esc, 8));
    }
  });
}

function decodeHex(s: string): string {
  const hex = s.replace(/\s+/g, "");
  let out = "";
  // Chromium writes 4-hex-digit (UTF-16BE) codes for embedded subset fonts; two-digit
  // codes appear in simple fonts. Try 4 first, and fall back when the length is odd.
  if (hex.length % 4 === 0) {
    for (let i = 0; i < hex.length; i += 4) {
      const code = parseInt(hex.slice(i, i + 4), 16);
      if (Number.isFinite(code) && code > 0 && code < 0xffff) out += String.fromCharCode(code);
    }
    // Subset fonts often map glyph ids, not Unicode. If almost nothing readable came
    // out, the hex was glyph indices and there is no text to recover this way.
    const readable = out.replace(/[^\x20-\x7e]/g, "").length;
    if (readable < out.length * 0.6) return "";
    return out;
  }
  for (let i = 0; i + 1 < hex.length; i += 2) {
    out += String.fromCharCode(parseInt(hex.slice(i, i + 2), 16));
  }
  return out;
}

function collapse(s: string): string {
  return s
    .replace(/\r\n?/g, "\n")
    .replace(/[ \t]+/g, " ")
    .split("\n")
    .map((l) => l.trim())
    .filter((l) => l.length > 0)
    .join("\n")
    .slice(0, 20_000);
}
