/**
 * src/db/seed.ts — `npm run db:seed`
 *
 * A demo portfolio for a mid-market property manager: three properties, eight
 * vendors, and a certificate file in every state the product has to handle —
 * compliant, expiring, deficient, expired, awaiting review, a parse that failed,
 * and a vendor with nothing on file at all.
 *
 * Every certificate is a real PDF, generated by lib/acord-sample.ts and run through
 * the actual intake path, so the review queue, the PDF viewer and the binder export
 * all have genuine documents behind them. Dates are relative to today, so the demo
 * stays sensible whenever it is run.
 *
 * Safe to re-run: it deletes the demo org and everything under it first, and it
 * refuses to touch a database that has any other org in it.
 */

import "@/lib/load-env";
import { eq, inArray } from "drizzle-orm";
import { closeDb, getDb } from "@/db";
import {
  auditLog,
  binderExports,
  certificateBlobs,
  certificates,
  chases,
  coverages,
  engagements,
  evaluations,
  orgs,
  properties,
  requirementTemplates,
  users,
  vendors,
} from "@/db/schema";
import { hashPassword } from "@/lib/auth";
import { DEFAULT_TEMPLATES } from "@/lib/requirement-presets";
import { addDays, plainDate } from "@/lib/dates";
import { buildSampleAcordPdf, compliantSample, type SampleAcord } from "@/lib/acord-sample";
import { intakeCertificate, parseCertificate } from "@/lib/certificates";
import { issueUploadToken } from "@/lib/tokens";
import { runTickForOrg } from "@/lib/tick";
import { persistEvaluations } from "@/lib/verdicts";
import { randomBytes } from "node:crypto";

const ORG_NAME = "Harbor Ridge Management";
const DEMO_PASSWORD = "harborridge2026";

const TODAY = plainDate(new Date(), "America/Los_Angeles");
const d = (offset: number) => addDays(TODAY, offset);

async function wipeDemoOrg(): Promise<void> {
  const db = getDb();
  const [org] = await db.select().from(orgs).where(eq(orgs.name, ORG_NAME));
  if (!org) return;

  const vendorRows = await db.select({ id: vendors.id }).from(vendors).where(eq(vendors.orgId, org.id));
  const vendorIds = vendorRows.map((v) => v.id);
  const certRows = vendorIds.length
    ? await db.select({ id: certificates.id }).from(certificates).where(inArray(certificates.vendorId, vendorIds))
    : [];
  const certIds = certRows.map((c) => c.id);
  const engagementRows = vendorIds.length
    ? await db.select({ id: engagements.id }).from(engagements).where(inArray(engagements.vendorId, vendorIds))
    : [];
  const engagementIds = engagementRows.map((e) => e.id);

  if (engagementIds.length) {
    await db.delete(chases).where(inArray(chases.engagementId, engagementIds));
    await db.delete(evaluations).where(inArray(evaluations.engagementId, engagementIds));
  }
  if (certIds.length) {
    await db.delete(coverages).where(inArray(coverages.certificateId, certIds));
    await db.delete(certificateBlobs).where(inArray(certificateBlobs.certificateId, certIds));
  }
  if (engagementIds.length) await db.delete(engagements).where(inArray(engagements.id, engagementIds));
  if (certIds.length) await db.delete(certificates).where(inArray(certificates.id, certIds));
  await db.delete(binderExports).where(eq(binderExports.orgId, org.id));
  await db.delete(auditLog).where(eq(auditLog.orgId, org.id));
  await db.delete(requirementTemplates).where(eq(requirementTemplates.orgId, org.id));
  if (vendorIds.length) await db.delete(vendors).where(inArray(vendors.id, vendorIds));
  await db.delete(properties).where(eq(properties.orgId, org.id));
  await db.delete(users).where(eq(users.orgId, org.id));
  await db.delete(orgs).where(eq(orgs.id, org.id));
}

interface VendorSpec {
  name: string;
  trade: string;
  contactName: string;
  contactEmail: string;
  agentName: string;
  agentEmail: string;
  phone: string;
  notes?: string;
  properties: string[];
  template: string;
  /** How this vendor's certificate is meant to land. */
  certificate:
    | { kind: "none" }
    | { kind: "letter" } // a PDF that is not a certificate: the failed-parse case
    | { kind: "acord"; spec: SampleAcord };
}

function acord(over: Partial<SampleAcord>): SampleAcord {
  return compliantSample({ holder: ORG_NAME, ...over });
}

const VENDORS: VendorSpec[] = [
  {
    name: "Kestrel Roofing LLC",
    trade: "Roofing",
    contactName: "Marisol Vega",
    contactEmail: "marisol@kestrelroofing.example",
    agentName: "Harbor & Main Insurance Agency",
    agentEmail: "renee@harborandmain.example",
    phone: "(503) 555-0148",
    notes: "Three-year MSA. Preferred roofer for the whole portfolio.",
    properties: ["Bayview Terrace", "Alder Court"],
    template: "Sub — structural",
    certificate: {
      kind: "acord",
      spec: acord({
        insured: "Kestrel Roofing LLC",
        certificateNumber: "CS-4471",
        issuedOn: d(-214),
        policies: [
          {
            type: "gl",
            policyNumber: "GL-4471-22",
            effectiveOn: d(-214),
            expiresOn: d(151),
            addlInsured: "Y",
            subrWaived: "Y",
            limits: [
              { label: "EACH OCCURRENCE", amount: "$1,000,000" },
              { label: "GENERAL AGGREGATE", amount: "$2,000,000" },
            ],
          },
          {
            type: "auto",
            policyNumber: "CA-8890-11",
            effectiveOn: d(-214),
            expiresOn: d(151),
            addlInsured: "Y",
            subrWaived: "N",
            limits: [{ label: "COMBINED SINGLE LIMIT", amount: "$1,000,000" }],
          },
          {
            type: "umbrella",
            policyNumber: "UMB-2210-04",
            effectiveOn: d(-214),
            expiresOn: d(151),
            addlInsured: "N",
            subrWaived: "N",
            limits: [{ label: "EACH OCCURRENCE", amount: "$5,000,000" }],
          },
          {
            type: "wc",
            policyNumber: "WC-5512-08",
            effectiveOn: d(-214),
            expiresOn: d(151),
            addlInsured: "N",
            subrWaived: "Y",
            limits: [{ label: "E.L. EACH ACCIDENT", amount: "$1,000,000" }],
          },
        ],
      }),
    },
  },
  {
    name: "Cordova Landscape & Irrigation",
    trade: "Landscaping",
    contactName: "Tomas Cordova",
    contactEmail: "tomas@cordovalandscape.example",
    agentName: "Cascade Risk Partners",
    agentEmail: "policies@cascaderisk.example",
    phone: "(503) 555-0177",
    notes: "Weekly grounds contract, April to November.",
    properties: ["Bayview Terrace"],
    template: "Standard vendor",
    certificate: {
      kind: "acord",
      spec: acord({
        insured: "Cordova Landscape & Irrigation",
        insurerA: "Tualatin Indemnity Company",
        producer: "Cascade Risk Partners",
        producerContact: "Wes Okafor | (503) 555-0193 | policies@cascaderisk.example",
        certificateNumber: "CS-4488",
        issuedOn: d(-183),
        description: "General liability per occurrence. No additional insured endorsement attached.",
        policies: [
          {
            type: "gl",
            policyNumber: "GL-9902-15",
            effectiveOn: d(-183),
            expiresOn: d(17),
            addlInsured: "N",
            subrWaived: "Y",
            limits: [
              { label: "EACH OCCURRENCE", amount: "$500,000" },
              { label: "GENERAL AGGREGATE", amount: "$1,000,000" },
            ],
          },
          {
            type: "auto",
            policyNumber: "CA-9902-16",
            effectiveOn: d(-183),
            expiresOn: d(17),
            addlInsured: "N",
            subrWaived: "N",
            limits: [{ label: "COMBINED SINGLE LIMIT", amount: "$1,000,000" }],
          },
          {
            type: "wc",
            policyNumber: "WC-3301-77",
            effectiveOn: d(-183),
            expiresOn: d(17),
            addlInsured: "N",
            subrWaived: "Y",
            limits: [{ label: "E.L. EACH ACCIDENT", amount: "$1,000,000" }],
          },
        ],
      }),
    },
  },
  {
    name: "Alder Mechanical",
    trade: "HVAC",
    contactName: "Dev Patel",
    contactEmail: "dev@aldermechanical.example",
    agentName: "Willamette Commercial Insurance",
    agentEmail: "certs@willamettecom.example",
    phone: "(971) 555-0102",
    notes: "Quarterly RTU maintenance across all three sites.",
    properties: ["Alder Court", "Cedar & 12th Renovation"],
    template: "Standard vendor",
    certificate: {
      kind: "acord",
      spec: acord({
        insured: "Alder Mechanical",
        insurerA: "Columbia Casualty Exchange",
        producer: "Willamette Commercial Insurance",
        producerContact: "Priya Raman | (971) 555-0110 | certs@willamettecom.example",
        certificateNumber: "CS-4502",
        issuedOn: d(-341),
        policies: [
          {
            type: "gl",
            policyNumber: "GL-7781-03",
            effectiveOn: d(-341),
            expiresOn: d(24),
            addlInsured: "Y",
            subrWaived: "Y",
            limits: [
              { label: "EACH OCCURRENCE", amount: "$1,000,000" },
              { label: "GENERAL AGGREGATE", amount: "$2,000,000" },
            ],
          },
          {
            type: "auto",
            policyNumber: "CA-7781-04",
            effectiveOn: d(-341),
            expiresOn: d(24),
            addlInsured: "Y",
            subrWaived: "Y",
            limits: [{ label: "COMBINED SINGLE LIMIT", amount: "$1,000,000" }],
          },
          {
            type: "wc",
            policyNumber: "WC-7781-05",
            effectiveOn: d(-341),
            expiresOn: d(24),
            addlInsured: "N",
            subrWaived: "Y",
            limits: [{ label: "E.L. EACH ACCIDENT", amount: "$1,000,000" }],
          },
        ],
      }),
    },
  },
  {
    name: "Pinehurst Electric",
    trade: "Electrical",
    contactName: "Ana Suarez",
    contactEmail: "ana@pinehurstelectric.example",
    agentName: "Cascade Risk Partners",
    agentEmail: "policies@cascaderisk.example",
    phone: "(503) 555-0121",
    notes: "On call for the Cedar & 12th renovation. Lapsed in July.",
    properties: ["Cedar & 12th Renovation"],
    template: "Sub — structural",
    certificate: {
      kind: "acord",
      spec: acord({
        insured: "Pinehurst Electric",
        insurerA: "Grayline Mutual Casualty Company",
        certificateNumber: "CS-4390",
        issuedOn: d(-396),
        policies: [
          {
            type: "gl",
            policyNumber: "GL-6620-31",
            effectiveOn: d(-396),
            expiresOn: d(-31),
            addlInsured: "Y",
            subrWaived: "Y",
            limits: [
              { label: "EACH OCCURRENCE", amount: "$1,000,000" },
              { label: "GENERAL AGGREGATE", amount: "$2,000,000" },
            ],
          },
          {
            type: "auto",
            policyNumber: "CA-6620-32",
            effectiveOn: d(-396),
            expiresOn: d(-31),
            addlInsured: "Y",
            subrWaived: "Y",
            limits: [{ label: "COMBINED SINGLE LIMIT", amount: "$1,000,000" }],
          },
          {
            type: "umbrella",
            policyNumber: "UMB-6620-33",
            effectiveOn: d(-396),
            expiresOn: d(-31),
            addlInsured: "N",
            subrWaived: "N",
            limits: [{ label: "EACH OCCURRENCE", amount: "$5,000,000" }],
          },
          {
            type: "wc",
            policyNumber: "WC-6620-34",
            effectiveOn: d(-396),
            expiresOn: d(-31),
            addlInsured: "N",
            subrWaived: "Y",
            limits: [{ label: "E.L. EACH ACCIDENT", amount: "$1,000,000" }],
          },
        ],
      }),
    },
  },
  {
    name: "Lantern Janitorial Services",
    trade: "Janitorial",
    contactName: "Grace Mbeki",
    contactEmail: "grace@lanternjanitorial.example",
    agentName: "Harbor & Main Insurance Agency",
    agentEmail: "renee@harborandmain.example",
    phone: "(503) 555-0164",
    notes: "Nightly common-area cleaning at Bayview and Alder.",
    properties: ["Bayview Terrace", "Alder Court"],
    template: "Low-risk service",
    certificate: {
      kind: "acord",
      spec: acord({
        insured: "Lantern Janitorial Services",
        insurerA: "Grayline Mutual Casualty Company",
        certificateNumber: "CS-4511",
        issuedOn: d(-96),
        description:
          "Additional insured status per written contract. Endorsement to follow under separate cover.",
        policies: [
          {
            type: "gl",
            policyNumber: "GL-1180-42",
            effectiveOn: d(-96),
            // The ADDL INSD column is blank on this one, which is what sends it to
            // review instead of into compliance.
            expiresOn: d(269),
            addlInsured: "",
            subrWaived: "",
            limits: [
              { label: "EACH OCCURRENCE", amount: "$1,000,000" },
              { label: "GENERAL AGGREGATE", amount: "$2,000,000" },
            ],
          },
        ],
      }),
    },
  },
  {
    name: "Vega Structural Engineering",
    trade: "Structural",
    contactName: "Ruben Vega",
    contactEmail: "ruben@vegastructural.example",
    agentName: "Willamette Commercial Insurance",
    agentEmail: "certs@willamettecom.example",
    phone: "(971) 555-0188",
    notes: "Sent a cover letter instead of the certificate. Parse failed; PDF is on file.",
    properties: ["Cedar & 12th Renovation"],
    template: "Sub — structural",
    certificate: { kind: "letter" },
  },
  {
    name: "Summit Elevator Service",
    trade: "Elevator",
    contactName: "Jodie Larkin",
    contactEmail: "jodie@summitelevator.example",
    agentName: "Ridgeline Insurance Brokers",
    agentEmail: "coi@ridgelinebrokers.example",
    phone: "(503) 555-0139",
    notes: "New vendor as of last month. Nothing on file yet.",
    properties: ["Bayview Terrace", "Alder Court"],
    template: "Standard vendor",
    certificate: { kind: "none" },
  },
  {
    name: "Meridian Fire & Safety",
    trade: "Fire & life safety",
    contactName: "Cal Okonjo",
    contactEmail: "cal@meridianfire.example",
    agentName: "Ridgeline Insurance Brokers",
    agentEmail: "coi@ridgelinebrokers.example",
    phone: "(503) 555-0155",
    notes: "Annual sprinkler and alarm inspection, all sites.",
    properties: ["Bayview Terrace", "Alder Court", "Cedar & 12th Renovation"],
    template: "Standard vendor",
    certificate: {
      kind: "acord",
      spec: acord({
        insured: "Meridian Fire & Safety",
        insurerA: "Columbia Casualty Exchange",
        producer: "Ridgeline Insurance Brokers",
        producerContact: "Nell Fairbanks | (503) 555-0170 | coi@ridgelinebrokers.example",
        certificateNumber: "CS-4520",
        issuedOn: d(-61),
        policies: [
          {
            type: "gl",
            policyNumber: "GL-3345-90",
            effectiveOn: d(-61),
            expiresOn: d(304),
            addlInsured: "Y",
            subrWaived: "Y",
            limits: [
              { label: "EACH OCCURRENCE", amount: "$2,000,000" },
              { label: "GENERAL AGGREGATE", amount: "$4,000,000" },
            ],
          },
          {
            type: "auto",
            policyNumber: "CA-3345-91",
            effectiveOn: d(-61),
            expiresOn: d(304),
            addlInsured: "Y",
            subrWaived: "Y",
            limits: [{ label: "COMBINED SINGLE LIMIT", amount: "$1,000,000" }],
          },
          {
            type: "wc",
            policyNumber: "WC-3345-92",
            effectiveOn: d(-61),
            expiresOn: d(304),
            addlInsured: "N",
            subrWaived: "Y",
            limits: [{ label: "E.L. EACH ACCIDENT", amount: "$1,000,000" }],
          },
        ],
      }),
    },
  },
];

const PROPERTIES = [
  {
    name: "Bayview Terrace",
    kind: "property" as const,
    address: "2214 SE Bayview Ave, Portland, OR 97202 — 96 units",
  },
  {
    name: "Alder Court",
    kind: "property" as const,
    address: "515 NW Alder St, Portland, OR 97209 — 48 units",
  },
  {
    name: "Cedar & 12th Renovation",
    kind: "project" as const,
    address: "1180 SE Cedar St, Portland, OR 97214 — gut renovation, 2026 season",
  },
];

/** A one-page cover letter: the PDF the failed-parse vendor actually sent. */
async function coverLetterPdf(vendorName: string): Promise<Uint8Array> {
  const { PDFDocument, StandardFonts, rgb } = await import("pdf-lib");
  const doc = await PDFDocument.create();
  const page = doc.addPage([612, 792]);
  const font = await doc.embedFont(StandardFonts.Helvetica);
  const bold = await doc.embedFont(StandardFonts.HelveticaBold);
  const ink = rgb(0.12, 0.14, 0.13);
  let y = 720;
  const put = (text: string, size = 11, f = font) => {
    page.drawText(text, { x: 56, y, size, font: f, color: ink });
    y -= size + 8;
  };
  put(vendorName, 14, bold);
  put("1180 SE Cedar St, Portland, OR 97214");
  y -= 12;
  put(`${ORG_NAME} — Compliance`, 11, bold);
  y -= 12;
  put("Re: insurance documents for the Cedar & 12th renovation");
  y -= 8;
  put("Hello,");
  put("Please find our W-9 and the signed subcontract attached. Our agent is");
  put("preparing the certificate of insurance and will send it directly to you");
  put("this week.");
  y -= 8;
  put("Regards,");
  put("Ruben Vega");
  return doc.save({ useObjectStreams: false });
}

async function main(): Promise<void> {
  const db = getDb();

  const otherOrgs = await db.select({ id: orgs.id, name: orgs.name }).from(orgs);
  const foreign = otherOrgs.filter((o) => o.name !== ORG_NAME);
  if (foreign.length) {
    console.error(
      `Refusing to seed: this database already has ${foreign.length} other org(s) (${foreign
        .map((o) => o.name)
        .join(", ")}). Seed into an empty database.`,
    );
    process.exitCode = 1;
    return;
  }

  await wipeDemoOrg();

  const [org] = await db
    .insert(orgs)
    .values({
      name: ORG_NAME,
      kind: "property_mgmt",
      plan: "trial",
      trialEndsAt: new Date(Date.now() + 11 * 86_400_000),
      timezone: "America/Los_Angeles",
      settings: {
        holderName: `${ORG_NAME} LLC`,
        chaseOffsets: [30, 14, 7, 1],
        tone: "plain",
        hookKey: `hk_${randomBytes(16).toString("hex")}`,
      },
    })
    .returning();

  const passwordHash = await hashPassword(DEMO_PASSWORD);
  await db.insert(users).values([
    {
      orgId: org.id,
      email: "dana@harborridge.example",
      name: "Dana Whitlock",
      role: "admin",
      passwordHash,
    },
    {
      orgId: org.id,
      email: "sam@harborridge.example",
      name: "Sam Iyer",
      role: "coordinator",
      passwordHash,
    },
  ]);

  const propertyRows = await db
    .insert(properties)
    .values(PROPERTIES.map((p) => ({ ...p, orgId: org.id })))
    .returning();
  const propertyByName = new Map(propertyRows.map((p) => [p.name, p]));

  const templateRows = await db
    .insert(requirementTemplates)
    .values(DEFAULT_TEMPLATES.map((t) => ({ ...t, orgId: org.id })))
    .returning();
  const templateByName = new Map(templateRows.map((t) => [t.name, t]));
  await db
    .update(orgs)
    .set({
      settings: { ...org.settings, defaultTemplateId: templateByName.get("Standard vendor")!.id },
    })
    .where(eq(orgs.id, org.id));

  for (const spec of VENDORS) {
    const [vendor] = await db
      .insert(vendors)
      .values({
        orgId: org.id,
        name: spec.name,
        trade: spec.trade,
        contactName: spec.contactName,
        contactEmail: spec.contactEmail,
        agentName: spec.agentName,
        agentEmail: spec.agentEmail,
        phone: spec.phone,
        notes: spec.notes ?? null,
      })
      .returning();
    await issueUploadToken(vendor.id);

    const template = templateByName.get(spec.template) ?? templateRows[0];
    for (const propertyName of spec.properties) {
      const property = propertyByName.get(propertyName);
      if (!property) continue;
      await db.insert(engagements).values({
        vendorId: vendor.id,
        propertyId: property.id,
        requirementTemplateId: template.id,
        startsOn: d(-365),
        status: "active",
      });
    }

    if (spec.certificate.kind === "none") continue;

    const bytes =
      spec.certificate.kind === "letter"
        ? await coverLetterPdf(spec.name)
        : await buildSampleAcordPdf(spec.certificate.spec);

    const intake = await intakeCertificate({
      orgId: org.id,
      vendorId: vendor.id,
      bytes,
      source: spec.certificate.kind === "letter" ? "inbound" : "portal",
      actor: `${spec.contactName} <${spec.contactEmail}> (upload portal)`,
      filename: `${spec.name.toLowerCase().replace(/[^a-z0-9]+/g, "-")}-coi.pdf`,
    });
    const outcome = await parseCertificate(intake.certificateId);
    console.log(`  ${spec.name}: ${outcome.status}${outcome.error ? ` — ${outcome.error}` : ""}`);
  }

  const [refreshed] = await db.select().from(orgs).where(eq(orgs.id, org.id));
  const persisted = await persistEvaluations(refreshed);
  console.log(`  ${persisted.written} verdicts recorded`);

  // One chase pass, so the timelines have history. DRY_RUN keeps it off the wire.
  const tick = await runTickForOrg(refreshed);
  console.log(
    `  chases: ${tick.chasesSent} sent, ${tick.chasesSkipped} skipped, ${tick.chasesFailed} failed`,
  );

  console.log(`\nSeeded ${ORG_NAME}.`);
  console.log(`  sign in: dana@harborridge.example / ${DEMO_PASSWORD}`);
}

main()
  .catch((err) => {
    console.error(err);
    process.exitCode = 1;
  })
  .finally(() => closeDb());
