/**
 * src/lib/pdf-text.ts
 *
 * A small, dependency-free PDF text extractor.
 *
 * Why hand-rolled: the rate-con pipeline needs the text of a PDF in two places
 * that must not depend on a model being reachable — the heuristic extractor
 * that runs when no ANTHROPIC_API_KEY is set, and the page count written onto
 * the document row. pdf-lib can build and merge PDFs but cannot read their text.
 *
 * What it does: walks the content streams, inflating the Flate-encoded ones,
 * and collects the strings passed to the text-showing operators (Tj, TJ, ', ").
 * That covers PDFs generated by software — which is every broker rate con that
 * arrived as an email attachment rather than a phone camera.
 *
 * What it deliberately does not do: OCR. A photographed rate con has no text
 * objects at all, and this returns an empty string for one. That is the honest
 * answer, and the pipeline treats it as "could not read" rather than as an empty
 * rate con — which is the whole point of the parse-honesty rule.
 */

import { inflateSync, inflateRawSync, unzipSync } from "node:zlib";

export interface PdfTextResult {
  text: string;
  /** Pages counted from the page tree. Zero when the structure is unreadable. */
  pageCount: number;
  /** True when there are content streams but no text objects — a scan. */
  looksScanned: boolean;
}

const DECODE_LIMIT = 40 * 1024 * 1024;

export function extractPdfText(bytes: Uint8Array): PdfTextResult {
  const buffer = Buffer.from(bytes);
  const pageCount = countPages(buffer);
  const streams = collectStreams(buffer);

  const chunks: string[] = [];
  let sawContentStream = false;
  for (const stream of streams) {
    const decoded = decodeStream(stream.data, stream.filters);
    if (!decoded) continue;
    if (!/\bBT\b|\bTj\b|\bTJ\b/.test(decoded.slice(0, 4096)) && !/\bTj\b|\bTJ\b/.test(decoded)) {
      continue;
    }
    sawContentStream = true;
    const text = harvestText(decoded);
    if (text.trim().length > 0) chunks.push(text);
  }

  const text = normaliseWhitespace(chunks.join("\n"));
  return {
    text,
    pageCount,
    looksScanned: pageCount > 0 && text.trim().length === 0 && !sawContentStream,
  };
}

/** Count `/Type /Page` objects — reliable enough, and never throws. */
function countPages(buffer: Buffer): number {
  const haystack = buffer.toString("latin1");
  const explicit = haystack.match(/\/Type\s*\/Page[^s]/g);
  if (explicit && explicit.length > 0) return explicit.length;
  const counts = [...haystack.matchAll(/\/Type\s*\/Pages[\s\S]{0,400}?\/Count\s+(\d+)/g)]
    .map((m) => Number(m[1]))
    .filter((n) => Number.isFinite(n) && n > 0);
  return counts.length > 0 ? Math.max(...counts) : 0;
}

interface RawStream {
  data: Buffer;
  filters: string[];
}

/**
 * Find every `stream … endstream` pair with its dictionary's filters. Byte
 * scanning rather than parsing the xref table: a rate con that has been
 * re-saved by three different tools often has a broken xref while its streams
 * are perfectly readable.
 */
function collectStreams(buffer: Buffer): RawStream[] {
  const streams: RawStream[] = [];
  const haystack = buffer.toString("latin1");
  let index = 0;
  while (streams.length < 500) {
    const start = haystack.indexOf("stream", index);
    if (start === -1) break;
    // Guard against matching the word inside `endstream`.
    if (haystack.slice(start - 3, start) === "end") {
      index = start + 6;
      continue;
    }
    const dictStart = haystack.lastIndexOf("<<", start);
    const dict = dictStart === -1 ? "" : haystack.slice(dictStart, start);
    let dataStart = start + "stream".length;
    if (haystack[dataStart] === "\r") dataStart += 1;
    if (haystack[dataStart] === "\n") dataStart += 1;
    const end = haystack.indexOf("endstream", dataStart);
    if (end === -1) break;
    const data = buffer.subarray(dataStart, end);
    if (data.length > 0 && data.length < DECODE_LIMIT) {
      streams.push({ data: Buffer.from(data), filters: filtersFrom(dict) });
    }
    index = end + "endstream".length;
  }
  return streams;
}

function filtersFrom(dict: string): string[] {
  const match = dict.match(/\/Filter\s*(\[[^\]]*\]|\/[A-Za-z0-9]+)/);
  if (!match) return [];
  return [...match[1].matchAll(/\/([A-Za-z0-9]+)/g)].map((m) => m[1]);
}

function decodeStream(data: Buffer, filters: string[]): string | null {
  const flate = filters.some((f) => f === "FlateDecode" || f === "Fl");
  const unsupported = filters.some((f) =>
    ["DCTDecode", "JPXDecode", "CCITTFaxDecode", "JBIG2Decode", "RunLengthDecode"].includes(f),
  );
  if (unsupported) return null;

  if (!flate) {
    // Uncompressed content stream, or one we can read as text anyway.
    return data.toString("latin1");
  }
  for (const attempt of [inflateSync, unzipSync, inflateRawSync]) {
    try {
      return attempt(data).toString("latin1");
    } catch {
      // Try the next inflater. A truncated stream is common in the wild and is
      // not a reason to fail the whole document.
    }
  }
  return null;
}

/**
 * Pull the strings out of a decoded content stream. Handles literal `(…)`
 * strings with escapes, hex `<…>` strings, TJ arrays, and the newline-showing
 * operators, and turns Td/TD/T*/Tm line moves into real line breaks so the
 * heuristic extractor sees a document shaped like the page.
 */
function harvestText(stream: string): string {
  let out = "";
  let i = 0;
  const pending: string[] = [];

  const flush = () => {
    if (pending.length > 0) {
      out += pending.join("");
      pending.length = 0;
    }
  };

  while (i < stream.length) {
    const ch = stream[i];

    if (ch === "(") {
      const { value, next } = readLiteral(stream, i);
      pending.push(value);
      i = next;
      continue;
    }
    if (ch === "<" && stream[i + 1] !== "<") {
      const close = stream.indexOf(">", i);
      if (close === -1) break;
      pending.push(readHex(stream.slice(i + 1, close)));
      i = close + 1;
      continue;
    }
    // Operators that end a line.
    if (/[A-Za-z*'"]/.test(ch)) {
      const match = /^(T\*|TD|Td|Tm|TJ|Tj|ET|BT|'|")/.exec(stream.slice(i));
      if (match) {
        const op = match[1];
        if (op === "T*" || op === "TD" || op === "Td" || op === "Tm" || op === "ET" || op === "'" || op === '"') {
          flush();
          out += "\n";
        } else if (op === "TJ" || op === "Tj") {
          flush();
        }
        i += op.length;
        continue;
      }
    }
    i += 1;
  }
  flush();
  return out;
}

function readLiteral(stream: string, start: number): { value: string; next: number } {
  let i = start + 1;
  let depth = 1;
  let value = "";
  while (i < stream.length) {
    const ch = stream[i];
    if (ch === "\\") {
      const nextCh = stream[i + 1];
      const simple: Record<string, string> = {
        n: "\n",
        r: "\r",
        t: "\t",
        b: "\b",
        f: "\f",
        "(": "(",
        ")": ")",
        "\\": "\\",
      };
      if (nextCh in simple) {
        value += simple[nextCh];
        i += 2;
        continue;
      }
      const octal = /^[0-7]{1,3}/.exec(stream.slice(i + 1, i + 4));
      if (octal) {
        value += String.fromCharCode(parseInt(octal[0], 8));
        i += 1 + octal[0].length;
        continue;
      }
      i += 2;
      continue;
    }
    if (ch === "(") {
      depth += 1;
      value += ch;
      i += 1;
      continue;
    }
    if (ch === ")") {
      depth -= 1;
      if (depth === 0) return { value, next: i + 1 };
      value += ch;
      i += 1;
      continue;
    }
    value += ch;
    i += 1;
  }
  return { value, next: i };
}

function readHex(body: string): string {
  const hex = body.replace(/[^0-9A-Fa-f]/g, "");
  let out = "";
  // UTF-16BE is the common encoding for hex strings in generated PDFs; two-byte
  // pairs whose high byte is zero are plain Latin-1.
  if (hex.length % 4 === 0 && /^(00[0-9A-Fa-f]{2})+$/.test(hex)) {
    for (let i = 0; i < hex.length; i += 4) {
      out += String.fromCharCode(parseInt(hex.slice(i + 2, i + 4), 16));
    }
    return out;
  }
  for (let i = 0; i + 1 < hex.length; i += 2) {
    out += String.fromCharCode(parseInt(hex.slice(i, i + 2), 16));
  }
  return out;
}

function normaliseWhitespace(text: string): string {
  return text
    .replace(/\r\n?/g, "\n")
    .replace(/[ \t ]+/g, " ")
    .split("\n")
    .map((line) => line.trim())
    .filter((line, index, all) => line.length > 0 || (index > 0 && all[index - 1].length > 0))
    .join("\n")
    .trim();
}
