/**
 * File storage behind one interface, so the backend is a deployment decision
 * rather than a rewrite.
 *
 * ARCHITECTURE.md calls for S3/R2 with presigned uploads. Two drivers ship here
 * instead, because they are the two that can be run and verified without cloud
 * credentials:
 *
 *  - **db** (default): blobs live in Postgres `file_blobs`. The only driver that
 *    works unchanged on Vercel, whose filesystem is read-only. Fine to a few MB
 *    per file, which is what the 10MB upload cap is for.
 *  - **local**: blobs live under `STORAGE_DIR`. Better for development; on a
 *    single VPS it is also a perfectly good production answer.
 *
 * An S3/R2 driver implements the same four methods and changes nothing above
 * this line. Storage keys are opaque and random — never derived from a client's
 * file name — so one portal can never guess another's key, and `files.portal_id`
 * remains the only thing that authorises a read.
 */

import { randomBytes } from "node:crypto";
import { eq } from "drizzle-orm";
import { getDb } from "@/db";
import { fileBlobs, type StorageDriver } from "@/db/schema";
import { env } from "@/lib/env";

export interface StoredObject {
  data: Buffer;
  contentType: string;
  size: number;
}

export interface StorageAdapter {
  readonly driver: StorageDriver;
  put(key: string, data: Buffer, contentType: string): Promise<void>;
  get(key: string): Promise<StoredObject | null>;
  delete(key: string): Promise<void>;
}

/** Random, opaque, and namespaced by portal for operational sanity only. */
export function newStorageKey(portalId: string, filename: string): string {
  const ext = /\.([a-zA-Z0-9]{1,8})$/.exec(filename)?.[1]?.toLowerCase() ?? "bin";
  return `${portalId}/${Date.now().toString(36)}-${randomBytes(8).toString("hex")}.${ext}`;
}

/* ------------------------------------------------------------ db driver --- */

const dbAdapter: StorageAdapter = {
  driver: "db",
  async put(key, data, contentType) {
    const db = getDb();
    await db
      .insert(fileBlobs)
      .values({ key, data, size: data.byteLength, contentType })
      .onConflictDoUpdate({
        target: fileBlobs.key,
        set: { data, size: data.byteLength, contentType },
      });
  },
  async get(key) {
    const db = getDb();
    const [row] = await db.select().from(fileBlobs).where(eq(fileBlobs.key, key));
    if (!row) return null;
    return { data: Buffer.from(row.data), contentType: row.contentType, size: row.size };
  },
  async delete(key) {
    const db = getDb();
    await db.delete(fileBlobs).where(eq(fileBlobs.key, key));
  },
};

/* --------------------------------------------------------- local driver --- */

async function localPath(key: string): Promise<{ dir: string; file: string }> {
  const path = await import("node:path");
  // Keys are generated by newStorageKey, but a traversal guard costs nothing and
  // stops a future caller from handing user input straight to the filesystem.
  const safe = key.replace(/\.\./g, "").replace(/^\/+/, "");
  const full = path.resolve(env.storageDir, safe);
  const root = path.resolve(env.storageDir);
  if (!full.startsWith(root + path.sep)) throw new Error("Refusing a storage key outside the root");
  return { dir: path.dirname(full), file: full };
}

const localAdapter: StorageAdapter = {
  driver: "local",
  async put(key, data, contentType) {
    const fs = await import("node:fs/promises");
    const { dir, file } = await localPath(key);
    await fs.mkdir(dir, { recursive: true });
    await fs.writeFile(file, data);
    await fs.writeFile(`${file}.type`, contentType, "utf8");
  },
  async get(key) {
    const fs = await import("node:fs/promises");
    const { file } = await localPath(key);
    try {
      const data = await fs.readFile(file);
      let contentType = "application/octet-stream";
      try {
        contentType = (await fs.readFile(`${file}.type`, "utf8")).trim() || contentType;
      } catch {
        /* no sidecar: fall back to the generic type */
      }
      return { data, contentType, size: data.byteLength };
    } catch {
      return null;
    }
  },
  async delete(key) {
    const fs = await import("node:fs/promises");
    const { file } = await localPath(key);
    await fs.rm(file, { force: true });
    await fs.rm(`${file}.type`, { force: true });
  },
};

const ADAPTERS: Record<StorageDriver, StorageAdapter> = {
  db: dbAdapter,
  local: localAdapter,
};

/** The configured driver, for writes. */
export function storage(): StorageAdapter {
  return ADAPTERS[env.storageDriver];
}

/**
 * The driver a specific row was written with, for reads. Files keep their driver
 * on the row, so switching `STORAGE_DRIVER` never orphans what is already stored.
 */
export function storageFor(driver: StorageDriver): StorageAdapter {
  return ADAPTERS[driver] ?? dbAdapter;
}
